variables:
  GIT_SUBMODULE_STRATEGY: recursive

build_tests_spike:
  stage: build
  image: registry.gitlab.kuleuven.be/distrinet/users/lowie-deferme/risc-v-hypervisor-extension/riscv-ci-env/toolchain:latest
  script:
    # Build tests for spike
    - ./run_tests.py --clean --build --emulator spike
  artifacts:
    when: always
    paths:
      - tests/*/build.log
      - tests/*/*.elf
    expire_in: 7 days

verif_tests_spike:
  stage: test
  image: registry.gitlab.kuleuven.be/distrinet/users/lowie-deferme/risc-v-hypervisor-extension/riscv-ci-env/spike:latest
  needs:
    - build_tests_spike
  script:
    - apt-get update && apt-get install python3-full -y
    - python3 -m venv venv && source venv/bin/activate
    - pip3 install pyyaml
    - ./run_tests.py --run --emulator spike
  artifacts:
    when: always
    paths:
      - tests/*/*.log
    expire_in: 7 days

stages:
  - build
  - test

include:
  # Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
  - template: Security/Secret-Detection.gitlab-ci.yml
