# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/espressif/conventional-precommit-linter
  rev: v1.3.0
  hooks:
    - id: conventional-precommit-linter
      stages: [commit-msg]
      args:
        - --types=feat,wip,fix,ci,refactor,revert,merge
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: trailing-whitespace
      stages: [pre-commit]
    - id: end-of-file-fixer
      stages: [pre-commit]
    - id: check-yaml
      stages: [pre-commit]
    - id: check-json
      stages: [pre-commit]
    - id: check-toml
      stages: [pre-commit]
    - id: check-added-large-files
      stages: [pre-commit]
    - id: check-merge-conflict
      stages: [pre-commit]
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v17.0.5
  hooks:
  - id: clang-format
    stages: [pre-commit]
    types_or: [c++, c]
- repo: https://github.com/doublify/pre-commit-rust
  rev: v1.0
  hooks:
    - id: fmt
    - id: cargo-check
    - id: clippy
